### ISSUE TITLE
update CHANGES from accumulated PRs

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDPOW#143]
We were not good updating CHANGES as parts of PRs. For release 0.7.0 #105 we need to manually update CHANGES from the git log messages.

Important PRs
- [x] #142: changes to scripts: default estimator changed, SI becomes default, stride=1 default
- [x] #141: additional solvent models
- [x] #134: scripts can choose estimator
- [x] organize CHANGES in sections

For future PRs, add CHANGES right away.
